services:
  # Nginx Service
  nginx:
    image: nginx:stable-alpine
    container_name: chat_nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - chat-network

  # PHP Service
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: chat_php
    volumes:
      - ./src:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - chat-network

  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: chat_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: chat
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - chat-network

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: chat_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: secret
    depends_on:
      - mysql
    networks:
      - chat-network

  # Redis Service (optional but recommended for Laravel)
  redis:
    image: redis:alpine
    container_name: chat_redis
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD:-secret}"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - chat-network

# Networks
networks:
  chat-network:
    driver: bridge

# Volumes
volumes:
  mysql_data:
  redis_data: